package obr;

import java.lang.String;

/**
 * A term may be either a variable or a constant.<br />
 * A constant is surround by simple quotes.
 * Note that two different types of constants exist : the first one is a classical constant added from a fact base.
 * The second one is a constant which have been generated by an existential rule application.
 * The "existential constants" start by a simple quote immediatly followed by an underscore.
 */
public class Term {

	/**
	 * Constructor.
	 * @param label The term label.
	 */
	public Term(String label) {
		_label = label;
	}

	/**
	 * Label getter.
	 * @return The term label.
	 */
	public String getLabel() {
		return _label;
	}

	/**
	 * Label setter.
	 * @param value The new label to set.
	 */
	public void setLabel(String value) {
		_label = value;
	}

	/**
	 * Allows to know if a term is a constant.
	 * @return True if the term is a constant, false otherwise.
	 */
	boolean isConstant() {
		return (_label.charAt(0) == '\'');
	}

	/**
	 * Allows to know if a term is a variable.
	 * @return True if the term is a variable, false otherwise.
	 */
	boolean isVariable() {
		return !isConstant();
	}

	/**
	 * Allows to know if a term is a constant which has been generated by an existential rule application.
	 * @return True if the term is a generated constant, false otherwise.
	 */
	boolean isExistential() {
		return (isConstant() && (_label.charAt(1)=='_'));
	}

	/**
	 * Converts the term into a String.
	 * @return The string representation of the term.
	 */
	@Override
	public String toString() {
		return _label;
	}

	/**
	 * Clones the term.
	 * @return A clone.
	 */
	@Override
	public Term clone() {
		return new Term(new String(_label));
	}

	/** Term label. */
	private String _label;

}


